name: remote ssh command
on:
  push:
    branches:
      - server
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SSH_PATH }}
            git pull
            pnpm install --frozen-lockfile
            NODE_ENV=production pnpm run -F server build
            cd server
            pm2 restart ecosystem.config.js
